version: '3'

volumes:
  mysql:
    driver: local
  solr:
    driver: local
  assets:
    driver: local
  file-storage:
    driver: local

services:

  mysql:
    restart: always
    image: mysql:5.7
    env_file: .env_deployment
    volumes:
      - mysql:/var/lib/mysql

  solr:
    restart: always
    image: solr:6.0
    ports:
       - "8983:8983"
    volumes:
      - solr:/opt/solr/server/solr/mycores
      - ./solr/config:/config
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - discovery-uat
      - /config


  # Rails
  web:
    restart: always
    image: discovery
    env_file: .env_deployment
    volumes:
      - assets:/app/public/assets/
      - file-storage:/app/storage/
    command: bundle exec puma -e uat
    depends_on:
      - mysql
      - solr
      - migration
      
  migration:
    build: .
    image: discovery
    command: bin/setup
    links:
      - mysql
    depends_on:
      - mysql

  nginx:
    restart: always
    image: nginx
    depends_on:
      - web
    env_file: .env_deployment
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - assets:/app/public/assets/
    ports:
      - "3002:80"