version: '3'

volumes:
  mysql:
    driver: local
  solr:
    driver: local
  assets:
    driver: local

services:

  mysql:
    restart: always
    image: mysql:5.7
    env_file: .env_deployment
    volumes:
      - mysql:/var/lib/mysql

  solr:
    restart: always
    image: ualbertalib/blacklight_solr_conf
    environment:
      - SOLR_HEAP=2g
      - VIRTUAL_HOST=solr.discovery.uat.library.ualberta.ca
    volumes:
      - solr:/opt/solr/server/solr/mycores
    ports:
      - "8983"

  mailcatcher:
    image: sj26/mailcatcher
    environment:
      - VIRTUAL_HOST=mail.discovery.uat.library.ualberta.ca
      - VIRTUAL_PORT=1080
    ports:
      - "1025"
      - "1080"

  # Rails
  web:
    restart: always
    image: ualbertalib/discovery:uat
    volumes:
      - assets:/app/public/assets/
      - ../discoveryData:/app/data
    command: bundle exec puma -e uat
    env_file: .env_deployment
    depends_on:
      - mysql
      - solr

  nginx:
    restart: always
    image: nginx
    depends_on:
      - web
    env_file: .env_deployment
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - assets:/app/public/assets/
    ports:
      - "80"