require_relative "./vocabulary"

class CurriculumModsVocabulary < Vocabulary

  set_terminology do |t|
    t.root(path: "mods:modsCollection", :xmlns => "", "xmlns:mods" => "http://www.loc.gov/mods/v3")
    t.abstract(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.accessCondition(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.affiliation(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.area(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.caption(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.cartographics(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.city(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.citySection(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.classification(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.continent(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.coordinates(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.copyInformation(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.copyrightDate(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.county(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.country(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.date(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.dateCaptured(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.dateCreated(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.dateIssued(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.dateModified(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.dateOther(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.description(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.descriptionStandard(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.detail(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.digitalOrigin(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.displayForm(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.edition(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.electronicLocator(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.end(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.enumerationAndChronology(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.etal(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.extension(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.extent(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.form(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.frequency(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.marcgt_genre(:namespace_prefix => "mods", :path=>"genre", :attributes => {"authority" => "marcgt"}, :index_as => :stored_searchable)
    t.genre(:namespace_prefix => "mods", :path=>"genre", :attributes=>{"authority"=>:none}, :index_as => :stored_searchable)
    t.geographic(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.geographicCode(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.hierarchicalGeographic(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.holdingExternal(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.holdingSimple(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.identifier(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.internetMediaType(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.island(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.issuance(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.language(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.languageOfCataloging(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.languageTerm(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.list(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.location(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.personalName(:namespace_prefix => "mods", :path=>"name", :attributes=>{"type" => "personal"}, :index_as => :stored_searchable)
    t.corporateName(:namespace_prefix => "mods", :path=>"name", :attributes=>{"type" => "corporate"}, :index_as => :stored_searchable)
    t.namePart(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.nonSort(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.note(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.number(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.occupation(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.originInfo(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.part(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.partName(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.partNumber(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.physicalDescription(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.place(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.placeTerm(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.projection(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.province(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.publisher(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.recordChangeDate(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.recordCreationDate(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.recordContentSource(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.recordIdentifier(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.id(:namespace_prefix => "mods", path: "recordIdentifier", :index_as => :stored_searchable)
    t.recordInfo(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.recordOrigin(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.reformattingQuality(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.region(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.relatedItem(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.role(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.roleTerm(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.scale(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.shelfLocator(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.start(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.state(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.subject(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.subLocation(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.subTitle(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.tableOfContents(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.targetAudience(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.temporal(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.territory(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.text(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.title(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.titleInfo(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.topic(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.total(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.typeOfResource(:namespace_prefix => "mods", :index_as => :stored_searchable)
    t.url(:namespace_prefix => "mods", :index_as => :stored_searchable)
  end

end
