### WARNING ###
##########################################################################################
# In Production, this file is now managed by ansible, starting Jan 29, 2016, to simplify
# a secure deployment.  Please know that changes you make to this file will be overwritten
# on a Production Blacklight server!
##########################################################################################

# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  profiles_edit_user: ualibraries
  profiles_edit_password: notAValidPassword
  secret_key_base: 30802ad6dc0da5bad5cef4969edf4edbb4c2c91ffd7b9263d23936674fad0fea4c192e762e6f12239485c610ef7b0ede733554fd2e2cbaed2c486f791b66c146
  solr_url: <%= ENV['SOLR_URL'] || 'http://localhost:8983/solr/discovery' %>
  rollbar_token: <%= ENV['ROLLBAR_TOKEN'] %>

test:
  secret_key_base: 30802ad6dc0da5bad5cef4969edf4edbb4c2c91ffd7b9263d23936674fad0fea4c192e762e6f12239485c610ef7b0ede733554fd2e2cbaed2c486f791b66c146
  solr_url: <%= ENV['SOLR_INGEST_URL'] || 'http://localhost:8983/solr/discovery-test' %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  solr_url: <%= ENV['SOLR_URL'] %>
  intercept_mail: true
  intercept_mail_address: 'dittest@ualberta.ca'
uat:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  database_url: <%= ENV['DATABASE_URL'] %>
  solr_url: <%= ENV['SOLR_URL'] %>
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  solr_url: <%= ENV['SOLR_URL'] %>
  google_analytics_token: <%= ENV['GOOGLE_ANALYTICS_TOKEN'] %>
