ActiveRecord::SessionStore::Session.create!([
  {session_id: "b9b206cbfc6a0e68d92252b87d1df38c", data: "BAh7CEkiEF9jc3JmX3Rva2VuBjoGRUZJIjFqQ0h6cEpodzkrM2RWK2lsQ1lt\nTGw2ZS9BbmV2dnNQZWRYdjIzSVc0cUVvPQY7AEZJIgxzaXRlX2lkBjsARmkG\nSSIKZmxhc2gGOwBUewdJIgxkaXNjYXJkBjsAVFsGSSIMc3VjY2VzcwY7AEZJ\nIgxmbGFzaGVzBjsAVHsGSSIMc3VjY2VzcwY7AEZJIhFQYWdlIGNyZWF0ZWQG\nOwBU\n"},
  {session_id: "38f03ca6a702e6f604246ac12ba23f91", data: "BAh7BkkiEF9jc3JmX3Rva2VuBjoGRUZJIjF6WE9CNmd0ZUlSaTFGcTZDU1ZD\nTEoremhMeWdoMklXLy9JeTdJUlpCMjNvPQY7AEY=\n"},
  {session_id: "1b32ab5e86b91ca64b4f424d9a1e0bd6", data: "BAh7B0kiEF9jc3JmX3Rva2VuBjoGRUZJIjFsczNDTmZJUlBkdFJwNWxhSmZB\ndEFwN25UK1AydG8zSE1VMXZzTzJFY0RNPQY7AEZJIgxzaXRlX2lkBjsARmkG\n"},
  {session_id: "c0055fcbee7fb4b5c8b0a221b4236766", data: "BAh7BkkiEF9jc3JmX3Rva2VuBjoGRUZJIjFGWCtnelZjVnkxTC8rSlhOTkph\nenp6aEVhWUdKVHRDTUpJdGZYTWRscCtBPQY7AEY=\n"},
  {session_id: "b50ca2018f49b215bebf1809acea4670", data: "BAh7BkkiEF9jc3JmX3Rva2VuBjoGRUZJIjEvSUxTK0FhcWxUbU5NQlZ3dEkx\ndFEzaU1DZVVwM1dnZDVDTmVEWG45ZUVvPQY7AEY=\n"},
  {session_id: "4dbf4a7bc3037b8bf832604bc810b42b", data: "BAh7BkkiEF9jc3JmX3Rva2VuBjoGRUZJIjFDYWtoM0pCb1hIYWt4WnZXbTk0\nRm9Ia2FIVktic3ZaZHQvZTQ5b0UyRExZPQY7AEY=\n"}
])
Profile.create!([
  {first_name: "Alexander", last_name: "Strilets", job_title: "Web Application Developer", unit: "its", email: "strilets@ualberta.ca", phone: "780-492-2052", campus_address: "cameron", expertise: "", introduction: "", publications: "", staff_since: nil, links: "", orcid: "", committees: "", personal_interests: "", opt_in: nil, slug: "alexander-strilets", liason: ""},
  {first_name: "Alfred", last_name: "Rinas", job_title: "BARD Assistant", unit: "access", email: "fred.rinas@ualberta.ca", phone: "780-248-1405", campus_address: "rutherford", expertise: "", introduction: "", publications: "", staff_since: nil, links: "", orcid: "", committees: "", personal_interests: "", opt_in: nil, slug: "alfred-rinas", liason: ""},
  {first_name: "Allison", last_name: "Sivak", job_title: "Public Services Librarian", unit: "education", email: "allison.sivak@ualberta.ca", phone: "780-492-1469", campus_address: "coutts", expertise: "", introduction: "", publications: "", staff_since: nil, links: "", orcid: "", committees: "", personal_interests: "", opt_in: nil, slug: "allison-sivak", liason: ""},
  {first_name: "Amanda", last_name: "Nagyl", job_title: "Catalog & Metadata Assistant", unit: "bib", email: "amanda.nagyl@ualberta.ca", phone: "780-492-7085", campus_address: "cameron", expertise: "", introduction: "", publications: "", staff_since: nil, links: "", orcid: "", committees: "", personal_interests: "", opt_in: nil, slug: "amanda-nagyl", liason: ""},
  {first_name: "Amber", last_name: "McIver", job_title: "Public Services Assistant", unit: "education", email: "amber.mciver@ualberta.ca", phone: "780-492-2210 ", campus_address: "coutts", expertise: "", introduction: "", publications: "", staff_since: nil, links: "", orcid: "", committees: "", personal_interests: "", opt_in: nil, slug: "amber-mciver", liason: ""},
  {first_name: "Amy", last_name: "Southgate", job_title: "Public Services Assistant", unit: "humanities", email: "southgat@ualberta.ca", phone: "780-492-1791", campus_address: "rutherford", expertise: "", introduction: "", publications: "", staff_since: nil, links: "", orcid: "", committees: "", personal_interests: "", opt_in: nil, slug: "amy-southgate", liason: ""},
  {first_name: "Andrea", last_name: "Quaiattini", job_title: "Academic Library Resident", unit: "health", email: "andrea.quaiattini@ualberta.ca", phone: "780-492-7905", campus_address: "scott", expertise: "", introduction: "", publications: "", staff_since: nil, links: "", orcid: "", committees: "", personal_interests: "", opt_in: nil, slug: "andrea-quaiattini", liason: ""},
  {first_name: "Angie", last_name: "Mandeville", job_title: "Public Services Manager", unit: "science", email: "angie.mandeville@ualberta.ca", phone: "780-492-5946", campus_address: "cameron", expertise: "", introduction: "", publications: "", staff_since: nil, links: "", orcid: "", committees: "", personal_interests: "", opt_in: nil, slug: "angie-mandeville", liason: ""},
  {first_name: "Anna", last_name: "Bombak", job_title: "Digital Content Specialist", unit: "digital", email: "anna.bombak@ualberta.ca", phone: "780-492-2202", campus_address: "cameron", expertise: "", introduction: "", publications: "", staff_since: nil, links: "", orcid: "", committees: "", personal_interests: "", opt_in: nil, slug: "anna-bombak", liason: ""},
  {first_name: "Anna", last_name: "Mah", job_title: "Senior Public Services Assistant", unit: "business", email: "anna.mah@ualberta.ca", phone: "780-492-5652", campus_address: "winspear", expertise: "", introduction: "", publications: "", staff_since: nil, links: "", orcid: "", committees: "", personal_interests: "", opt_in: nil, slug: "anna-mah", liason: ""},
  {first_name: "Anne", last_name: "Carr-Wiggin", job_title: "NEOS Manager & Indigenous Initiatives", unit: "external", email: "anne.carr-wiggin@ualberta.ca", phone: "780-492-7907", campus_address: "cameron", expertise: "", introduction: "", publications: "", staff_since: nil, links: "", orcid: "", committees: "", personal_interests: "", opt_in: nil, slug: "anne", liason: ""},
  {first_name: "April", last_name: "Fodor", job_title: "Web Content Specialist", unit: "its", email: "april.fodor@ualberta.ca", phone: "780-492-4682", campus_address: "cameron", expertise: "", introduction: "", publications: "", staff_since: nil, links: "", orcid: "", committees: "", personal_interests: "", opt_in: nil, slug: "april-fodor", liason: ""},
  {first_name: "Arden", last_name: "Hill", job_title: "Public Services Assistant", unit: "health", email: "awhill@ualberta.ca", phone: "780-492-3899", campus_address: "scott", expertise: "", introduction: "", publications: "", staff_since: nil, links: "", orcid: "", committees: "", personal_interests: "", opt_in: nil, slug: "arden-hill", liason: ""},
  {first_name: "Beau", last_name: "Sapach", job_title: "Network Analyst", unit: "its", email: "beau.sapach@ualberta.ca", phone: "780-492-4181", campus_address: "cameron", expertise: "", introduction: "", publications: "", staff_since: nil, links: "", orcid: "", committees: "", personal_interests: "", opt_in: nil, slug: "beau-sapach", liason: ""},
  {first_name: "Bernadette", last_name: "Giblin", job_title: "Acquisitions Assistant", unit: "collections", email: "giblin@ualberta.ca", phone: "780-492-7093", campus_address: "cameron", expertise: "", introduction: "", publications: "", staff_since: nil, links: "", orcid: "", committees: "", personal_interests: "", opt_in: nil, slug: "bernadette-giblin", liason: ""},
  {first_name: "Bernard", last_name: "Offengenden", job_title: "Public Service Assistant", unit: "humanities", email: "", phone: "", campus_address: "rutherfordsouth", expertise: "", introduction: "", publications: "", staff_since: nil, links: "", orcid: "", committees: "", personal_interests: "", opt_in: nil, slug: "bernard-offengenden", liason: ""},
  {first_name: "Beverly", last_name: "Diotte", job_title: "Public Services Assistant\t", unit: "health", email: "beverly.diotte@ualberta.ca", phone: "780-492-3899", campus_address: "scott", expertise: "", introduction: "", publications: "", staff_since: nil, links: "", orcid: "", committees: "", personal_interests: "", opt_in: nil, slug: "beverly-diotte", liason: ""},
  {first_name: "Boguslawa", last_name: "Stanicki", job_title: "Access Services Assistant", unit: "access", email: "betty.stanicki@ualberta.ca", phone: "780-248-1402", campus_address: "rutherford", expertise: "", introduction: "", publications: "", staff_since: nil, links: "", orcid: "", committees: "", personal_interests: "", opt_in: nil, slug: "boguslawa-stanicki", liason: ""},
  {first_name: "Bonnie", last_name: "Gallinger", job_title: "Public Services Assistant", unit: "science", email: "bonnie.gallinger@ualberta.ca", phone: "780-492-7909", campus_address: "cameron", expertise: "", introduction: "", publications: "", staff_since: nil, links: "", orcid: "", committees: "", personal_interests: "", opt_in: nil, slug: "bonnie-gallinger", liason: ""},
  {first_name: "Brenda", last_name: "Wolfe", job_title: "Public Services Assistant", unit: "health", email: "brenda.wolfe@ualberta.ca", phone: "780-492-5154", campus_address: "scott", expertise: "", introduction: "", publications: "", staff_since: nil, links: "", orcid: "", committees: "", personal_interests: "", opt_in: nil, slug: "brenda-wolfe", liason: ""},
  {first_name: "Brian", last_name: "Stearns", job_title: "Metadata & Catalog Librarian", unit: "bib", email: "brian.stearns@ualberta.ca", phone: "780-492-7603", campus_address: "cameron", expertise: "", introduction: "", publications: "", staff_since: nil, links: "", orcid: "", committees: "", personal_interests: "", opt_in: nil, slug: "brian-stearns", liason: ""}
])
